language: dart
sudo: false
dart:
  - dev

dart_task:
  - test: -p vm,firefox
  - dartfmt

matrix:
  include:
    - dart: dev
      dart_task: dartanalyzer --fatal-warnings .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
