language: dart

dart:
  - dev

dart_task:
  - test: -p vm,firefox
  - dartfmt
  - dartanalyzer: --fatal-warnings --fatal-hints .

matrix:
  include:
    - dart: 2.6.0
      dart_task:
        dartanalyzer: --fatal-warnings --fatal-hints .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
