name: pop_pop_win
author: Dart Team <misc@dartlang.org>
description: '"Pop, Pop, Win!" is an implementation of Minesweeper in Dart.'
homepage: https://github.com/dart-lang/sample-pop_pop_win
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  stagexl: '^1.0.0'
dev_dependencies:
  browser: '^0.10.0'
  dart_to_js_script_rewriter: ^1.0.0
  test: '^0.12.0'
transformers:
- test/pub_serve:
    $include: test/**_test.dart
- $dart2js:
    commandLineOptions:
      - --show-package-warnings
      - --dump-info
      - --no-frequency-based-minification
      - --trust-type-annotations
      - --trust-primitives
- dart_to_js_script_rewriter
