name: ci

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 0"

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  # Check code formatting and static analysis on a single OS (linux)
  # against Dart dev and 2.8.4
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [dev, 2.8.4]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v0.3
        with:
          sdk: ${{ matrix.sdk }}
      - id: install
        name: Install dependencies
        run: pub get
      - name: Check formatting
        run: dartfmt -n --set-exit-if-changed .
        if: always() && steps.install.outcome == 'success'
      - name: Analyze code
        run: dartanalyzer --fatal-infos .
        if: always() && steps.install.outcome == 'success'

  test:
    needs: analyze
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        sdk: [dev, 2.8.4]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v0.3
        with:
          sdk: ${{ matrix.sdk }}
      - id: install
        name: Install dependencies
        run: pub get
      - name: Run VM tests
        run: pub run test --platform vm
        if: always() && steps.install.outcome == 'success'
      - name: Run Chrome tests
        run: pub run test --platform chrome
        if: always() && steps.install.outcome == 'success'
